# Generated by Django 3.2.9 on 2023-04-26 18:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('user_email', models.EmailField(max_length=254, primary_key=True, serialize=False, unique=True, verbose_name='Почта')),
                ('user_id', models.PositiveBigIntegerField(verbose_name='Telegram ID')),
                ('username', models.CharField(blank=True, max_length=256, null=True, verbose_name='Ник в TG')),
                ('first_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Имя')),
                ('last_name', models.CharField(blank=True, max_length=256, null=True, verbose_name='Фамилия')),
                ('city', models.CharField(blank=True, choices=[('Moscow', 'Москва'), ('Volgograd', 'Волгоград')], max_length=256, null=True, verbose_name='Город')),
                ('mail_status', models.CharField(blank=True, choices=[('active', 'Активна'), ('inactive', 'Отключена')], max_length=256, null=True, verbose_name='Статус')),
                ('activity', models.CharField(blank=True, choices=[('registered', 'Зарегистрирован'), ('game', 'Играет'), ('pause', 'Пауза'), ('removed', 'Удален')], max_length=256, null=True, verbose_name='Активность')),
                ('language_code', models.CharField(blank=True, help_text='Язык пользователя Telegram', max_length=8, null=True, verbose_name='Язык')),
                ('is_blocked_bot', models.BooleanField(default=False, verbose_name='Заблокирован?')),
                ('is_admin', models.BooleanField(default=False, verbose_name='Администратор?')),
            ],
            options={
                'verbose_name': 'Пользователь',
                'verbose_name_plural': 'Пользователи',
            },
        ),
        migrations.CreateModel(
            name='UserActionLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Изменен')),
                ('action', models.CharField(max_length=128)),
                ('text', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='users.user')),
            ],
            options={
                'ordering': ('-created_at',),
                'abstract': False,
            },
        ),
    ]
