# Generated by Django 3.2.9 on 2023-05-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_email_emailcode_usermeeting'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Email',
        ),
    ]
