# Generated by Django 3.2.9 on 2023-04-17 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_useractionlog'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='account_creation_date',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='activity',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='user',
            name='mail_status',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
