# Generated by Django 3.2.9 on 2023-04-17 18:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_auto_20230417_2110'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='city',
            field=models.CharField(blank=True, choices=[('Moscow', 'Москва'), ('Volgograd', 'Волгоград')], max_length=256, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='activity',
            field=models.CharField(blank=True, choices=[('registered', 'Зарегистрирован'), ('game', 'Играет'), ('pause', 'Пауза'), ('removed', 'Удален')], max_length=256, null=True),
        ),
    ]
