# Generated by Django 3.2.9 on 2023-04-17 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0012_remove_user_deep_link'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='email',
            new_name='user_email',
        ),
    ]
